[package]
name = "files-4kb"
version = "1.0.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = "fat"
strip = true
opt-level = 3
panic = "abort"

[dependencies]
human_bytes = {version = "0.3.1", features = ["fast"]}
